services:

    #模板扩展
    geo.twig.geo_extension:
        class: Henter\GEOBundle\Twig\GEOExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container]

    #fuck coordinate in China
    geo.location:
        class: Henter\GEOBundle\Util\LocationService
